SBNSoftware/sbnobj

- ups/product_deps
initial thing ready to merge, but may want more updates
> updated cmake lists and get initial dependence on lardataobj

- sbnobj/ICARUS/PMT/Trigger/Data/TriggerGateData.h
- sbnobj/ICARUS/PMT/Trigger/Data/TriggerGateData.tcc
A sloppy piece of code presented bugs that went unnoticed for years.
This is a data product currently used by ICARUS trigger simulation.
> Fixed a bug in icarus::trigger::TriggerGateData code.

- sbnobj/Common/PMT/Data/V1730Configuration.cxx
- sbnobj/Common/PMT/Data/V1730Configuration.h
- sbnobj/Common/PMT/Data/classes_def.xml
This is actually DAQ configuration rather than PMT readout.
I'd say "close enough".
> Added TimeTagForTimeStamp parameter to PMT configuration data object

- sbnobj/Common/CMakeLists.txt
- sbnobj/Common/Calibration/CMakeLists.txt
- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes.h
- sbnobj/Common/Calibration/classes_def.xml
New objects. Orthogonal to existing stuff.
> New track calo skimmer module for ICARUS calibration stuff.

- sbnobj/Common/Reco/Stub.cc
- sbnobj/Common/Reco/Stub.cxx
- sbnobj/Common/Reco/Stub.h
- sbnobj/Common/Reco/VertexHit.h
- sbnobj/Common/Reco/classes_def.xml
A few updates to the objects saved by stub reconstruction.
> Updates to Stub objects

- sbnobj/Common/CMakeLists.txt
- sbnobj/Common/EventGen/CMakeLists.txt
- sbnobj/Common/EventGen/MeVPrtl/CMakeLists.txt
- sbnobj/Common/EventGen/MeVPrtl/KaonParent.cxx
- sbnobj/Common/EventGen/MeVPrtl/KaonParent.h
- sbnobj/Common/EventGen/MeVPrtl/MeVPrtlDecay.h
- sbnobj/Common/EventGen/MeVPrtl/MeVPrtlFlux.h
- sbnobj/Common/EventGen/MeVPrtl/MeVPrtlTruth.cxx
- sbnobj/Common/EventGen/MeVPrtl/MeVPrtlTruth.h
- sbnobj/Common/EventGen/MeVPrtl/classes.h
- sbnobj/Common/EventGen/MeVPrtl/classes_def.xml
Adds in products to sbnobj for MeVPrtl Event Generation.
> Refactor configs and products out of sbncode for MeVPrtl Event Generator

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
Also save channel number for per-wire stuff
> Save More Truth Information in Calibration NTuple

- sbnobj/SBND/CMakeLists.txt
- sbnobj/SBND/Trigger/CMakeLists.txt
- sbnobj/SBND/Trigger/classes.h
- sbnobj/SBND/Trigger/classes_def.xml
- sbnobj/SBND/Trigger/pmtTrigger.cc
- sbnobj/SBND/Trigger/pmtTrigger.hh
Definitions for the data product created by the pmtTriggerProducer module in SBNSoftware/sbndcode#214
> Created PMT Hardware Trigger simulation producer

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
Refine truth matching variables; add in SCE corrected versions where useful; add in an addition Hit truth backtracking method.
> Calibration NTuple Update

- sbnobj/Common/CRT/classes.h
- sbnobj/Common/CRT/classes_def.xml
Required for https://github.com/SBNSoftware/sbndcode/pull/171
> Added CRT Hit to anab::T0 assns

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
> Clarify hit-position information. Add in separate fields for the SpacePoint and Track-TrajectoryPoint.

- sbnobj/ICARUS/CRT/CRTData.hh
Changes needed for icaruscode pull request SBNSoftware/icaruscode#315. They should be approved (or not) together.
> Added fields to CRTData struct

- sbnobj/Common/CRT/CRTHit.hh
- sbnobj/Common/CRT/CRTTrack.hh
- sbnobj/Common/CRT/classes_def.xml
Same as PR #52, but for release SBN2022A.
> Change Time Data Type for CRTHit and CRTTrack

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
Copy of https://github.com/SBNSoftware/sbnobj/pull/58 but intended for the develop branch.
> Update Caloskim NTuple on Develop

- sbnobj/Common/EventGen/MeVPrtl/MeVPrtlFlux.h
- sbnobj/Common/EventGen/MeVPrtl/classes_def.xml
This commit is dependent on sbncode pull request #340 (https://github.com/SBNSoftware/sbncode/pull/340) and on sbndcode Pull request https://github.com/SBNSoftware/sbncode/pull/324 (https://github.com/SBNSoftware/sbndcode/pull/324)
> Add polarization as a variable for MeVPrtFlux

- sbnobj/Common/Reco/OpT0FinderResult.cc
- sbnobj/Common/Reco/OpT0FinderResult.h
- sbnobj/Common/Reco/classes.h
- sbnobj/Common/Reco/classes_def.xml
created new OpT0Finder data products, these replace the T0 objects storing OpT0Finder results in `sbndcode`.
> SBND OpT0Finder Objects

- sbnobj/Common/Reco/TPCPMTBarycenterMatch.cc
- sbnobj/Common/Reco/TPCPMTBarycenterMatch.h
- sbnobj/Common/Reco/classes.h
- sbnobj/Common/Reco/classes_def.xml
Associated with the following requests in other packages:
icarusalg - https://github.com/SBNSoftware/icarusalg/pull/77
sbnanaobj - https://github.com/SBNSoftware/sbnanaobj/pull/113
sbncode - https://github.com/SBNSoftware/sbncode/pull/401
icaruscode - https://github.com/SBNSoftware/icaruscode/pull/646
> Barycenter flash match for production patch

- sbnobj/Common/PMT/Data/classes.h
This PR removes an unnecessary instantiation of a class and adds a missing header file.
> Cleanup classes.h file

- sbnobj/Common/Analysis/CMakeLists.txt
- sbnobj/Common/CRT/CMakeLists.txt
- sbnobj/Common/EventGen/MeVPrtl/CMakeLists.txt
- sbnobj/Common/PMT/Data/CMakeLists.txt
- sbnobj/Common/POTAccounting/CMakeLists.txt
- sbnobj/Common/Reco/CMakeLists.txt
- sbnobj/Common/SBNEventWeight/CMakeLists.txt
- sbnobj/Common/Trigger/CMakeLists.txt
- sbnobj/ICARUS/CRT/CMakeLists.txt
- sbnobj/ICARUS/PMT/Data/CMakeLists.txt
- sbnobj/ICARUS/PMT/Trigger/Data/CMakeLists.txt
- sbnobj/SBND/CRT/CMakeLists.txt
- sbnobj/SBND/Commissioning/CMakeLists.txt
- sbnobj/SBND/Timing/CMakeLists.txt
- sbnobj/SBND/ToF/CMakeLists.txt
- sbnobj/SBND/Trigger/CMakeLists.txt
- ups/product_deps
This is to be used for testing larsoft `v10_00_00rc1`.
> Update CMakeLists.txt files and product versions

- sbnobj/SBND/CRT/classes_def.xml
For SBNSoftware/sbndcode#690 to work we need this extra dictionary for the new branch type.
> Add Dictionary

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
> Calib NTuple CRT Timing Additions - Production 2025A Version
