SBNSoftware/sbnobj

- sbnobj/Common/Reco/CMakeLists.txt
- sbnobj/Common/Reco/MergedTrackInfo.hh
- sbnobj/Common/Reco/Stub.h
- sbnobj/Common/Reco/VertexHit.h
- sbnobj/Common/Reco/classes_def.xml
During the porting to the new repository structure, a bunch of TVector's were apparently changed to geo-types. This breaks a bunch of existing code (including code that was merged into sbncode).
This commit reverts those changes.
> Revert new products to use TVector's instead of geo types.

- sbnobj/Common/CMakeLists.txt
- sbnobj/Common/SBNEventWeight/CMakeLists.txt
- sbnobj/Common/SBNEventWeight/EventWeightMap.cc
- sbnobj/Common/SBNEventWeight/EventWeightMap.h
- sbnobj/Common/SBNEventWeight/EventWeightParameterSet.cxx
- sbnobj/Common/SBNEventWeight/EventWeightParameterSet.h
- sbnobj/Common/SBNEventWeight/classes.h
- sbnobj/Common/SBNEventWeight/classes_def.xml
- ups/product_deps
This pull request adds data products for SBN event weights (stored on the `art::Event`s) and parameters (stored on the `art::Run`s). The classes are located in a new directory `Common/SBNEventWeight`.
The former (weights) are simply a `typedef`, while the latter (parameters) are a new class. That class stores data in public members using only basic and STL types. Member functions related to initialization do have nontrivial logic and have library (CLHEP) dependencies, and currently handle error conditions with `assert` to avoid any LArSoft (specifically `cetlib`) dependence. The initialization code can be relocated to e.g. `sbncode` if preferred.
This should be reviewed alongside the `sbndcode` Pull Request which contains the framework and calculator code: …
> SBNEventWeight

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
Updates to objects for track-calo skimming in ICARUS. Adds in truth information and hits near the end-point of the track.
> Updates to TrackSkim object. Add in end-point-hit information and truth information.

- sbnobj/Common/Reco/Stub.h
- sbnobj/Common/Reco/VertexHit.h
- sbnobj/Common/Reco/classes_def.xml
Cleans up stub objects (removes TVector's and other unused variables) and adds in information necessary to incorporate changes for Space Charge.
> Updates to Stub Objects for Space Charge

- sbnobj/Common/Calibration/CMakeLists.txt
_Edit: moved the explanation into an issue ticket (#24) for ease of lookup._
The header in this directory, `sbnobj/Common/Calibration/TrackCaloSkimmerObj.h`, was not installed.
This prevents on-the-fly compilation by ROOT, and therefore loading files with this data object.
While I have tested the fix itself, **this is a GitHub commit, which has not been tested _at all_.** Integration test should tell.
> Fix to Missing FileEntry for sbnobj/Common/Calibration/TrackCaloSkimmerObj.h

- sbnobj/ICARUS/CRT/CRTData.hh
What harm could an empty constructor (`CRTData() {}`) ever do?
This is one: it prevents the initialisation of simple data types during construction.
In this case, `CRTData` is a simple plain-old-data structure with integers and an array. A default initialisation sets all the integers _and the elements of the array_ to a default value (`0`). If this does not happen, the simple data type variables are _not initialised_ at all.
Depending on the context, one way or the other may be desired. The only reason to choose the latter is probably just performance, but setting memory to `0` is usually decently fast so it's often not a concern.
In the case of this data structure, it often happens that part of the data is not filled (not all FEB have 64 channels). In this case I argue that the most …
> Removed empty constructor from `CRTData`

- sbnobj/Common/CRT/CRTHit.hh
- sbnobj/Common/CRT/CRTTrack.hh
- sbnobj/Common/CRT/classes_def.xml
As discussed in issue #51, this PR changes the data type for time variables from `unsigned int` to `double` for both CRTHits and CRTTracks. Resolves #51.
The main change is in commit [393f861](https://github.com/SBNSoftware/sbnobj/pull/52/commits/393f8610371f0903303c8874779dd75917bbab68).
> Change Time Data Type for CRTHit and CRTTrack

- sbnobj/Common/SBNEventWeight/EventWeightParameterSet.h
For the multisigma modes where we fill `fWidths`, `fWidth` was not initialized and cause errors when we compare two objects like in https://github.com/SBNSoftware/sbncode/blob/d40d6334c05aaae67cb3ef3ebfb97ec18549773c/sbncode/CAFMaker/CAFMaker_module.cc#L469. This is updated, and also we have to check `fWidths` in  `operator==`.
> Initialize fWidth

- sbnobj/Common/CMakeLists.txt
- sbnobj/Common/Trigger/BeamBits.h
- sbnobj/Common/Trigger/CMakeLists.txt
- sbnobj/Common/Trigger/ExtraTriggerInfo.cxx
- sbnobj/Common/Trigger/ExtraTriggerInfo.h
- sbnobj/Common/Trigger/classes.h
- sbnobj/Common/Trigger/classes_def.xml
Main change is addition of trigger information and moving the `sbn::ExtraTriggerInfo` object from icaruscode to sbnobj for getting the needed object for this PR accessible to ICARUS and SBND.
Tested on ICARUS data from raw -> CAF stage and successfully computed the time within the beam gate for the data. 
Depends on equivalent PRs in icaruscode, sbncode, and sbnobj
> Addition of trigger information in CAF files. Addition of time within beam gate to the CAFs for ICARUS data

- sbnobj/ICARUS/PMT/Trigger/Data/TriggerGateData.tcc
This is a completely trivial change that lay on my branch forever. It changes the text output of a data product, with no consequence whatsoever.
I am going to stick to GitHub suggestion for the reviewer selection... but I claim that if it compiles it does not need further review.
Well, a trigger gate object is a discriminated multi-level gate in time, meaning that it describes something that starts at level `0`, then it may rise to level `1`, then after a while to level `2` or back to `0`, and so forth. The output to stream shows the time when these changes happen. The change introduces printing also the level entered at the time of the change (unless it's `0` or `1`). This exception is because most often this object is used for a simple discriminator where levels are only `0` and `1`, in …
> Output of trigger gate object dump expanded.

- sbnobj/Common/Trigger/BeamBits.h
- sbnobj/Common/Trigger/ExtraTriggerInfo.cxx
- sbnobj/ICARUS/PMT/Trigger/Data/TriggerGateData.tcc
These two additions add a tiny bit of information to the dump of trigger and trigger gates.
This is not important enough to call for a new release on its own: please merge it when a new release is due because of other requests.
Picking @jzettle as reviewer because he's out of luck; not much to review anyway.
> Additions to trigger dump information

- sbnobj/Common/Reco/CRUMBSResult.cc
- sbnobj/Common/Reco/CRUMBSResult.h
- sbnobj/Common/Reco/classes_def.xml
Contains the required updates to `CRUMBSResult` in order to store separate signal specific versions of the CRUMBS score.
> CRUMBS Multi Signal

- sbnobj/SBND/Trigger/classes_def.xml
Adding a wrapper to put the CRT metrics into a vector. Parent PR in sbndcode: [PR #314](https://github.com/SBNSoftware/sbndcode/pull/314/files)
> trigger metrics bug fix 

- sbnobj/Common/CRT/CRTHit.hh
This line was edited a while ago when T1 of CRTHit was not working properly. Now that we have correct numbers, and by the fact the T1 is a relative time not a timestamp, we only need ts1_ns to describe entire T1.
> Fix sbn::crt::ts1()

- sbnobj/Common/Trigger/ExtraTriggerInfo.h
This is a simple addition to this data product interface.
The new member function returns the trigger time with respect to the beam gate time, and I added it because the conversions to signed are tedious if written correctly, so I'd rather do it once.
This is a gregarious request that should be merged only when some other thing is being merged in `sbnobj`: it's not worth its own release.
Also note that this is a GitHub edit — I trust on the C.I. test to tell if it does not compile.
I also let you choose whom to ask to review it (a.k.a. I have no idea).
> Added sbn::ExtraTriggerInfo::triggerFromBeamGate()

- sbnobj/Common/CRT/CRTPMTMatching.hh
- sbnobj/Common/CRT/classes.h
- sbnobj/Common/CRT/classes_def.xml
This pull request modifies where the CRTPMTMatching data product introduced in icaruscode v09_75_01 (from pull request https://github.com/SBNSoftware/icaruscode/pull/579) is defined to be in a SBN common area (sbnobj) (`icarus::crt::CRTPMTMatching` -> `sbn::crt::CRTPMTMatching`) so that the matching variables can be read in to the CAFs.
This is part of a PR pair that moves CRTPMTMatching definitions from `icaruscode/IcarusObj` to `sbnobj/Common`: 
* icaurscode PR #[594](https://github.com/SBNSoftware/icaruscode/pull/594) 
* sbnobj PR #[86](https://github.com/SBNSoftware/sbnobj/pull/86)
> move CRTPMTMatching definitions from icaurscode to sbnobj

- sbnobj/ICARUS/CMakeLists.txt
- sbnobj/ICARUS/TPC/CMakeLists.txt
- sbnobj/ICARUS/TPC/ChannelROI.cxx
- sbnobj/ICARUS/TPC/ChannelROI.h
- sbnobj/ICARUS/TPC/classes.h
- sbnobj/ICARUS/TPC/classes_def.xml
Moving ChannelROI to SBNObj lets SBND use it and allows for a common release of TITUS
> moving ChannelROI to sbnobj

- sbnobj/SBND/CRT/FEBData.cxx
- sbnobj/SBND/CRT/FEBData.hh
This PR adds the flags & unixtime fields to the FEBData object to better represent the real data.
> Add flags & unixtime fields to FEBData object

- sbnobj/Common/CRT/classes_def.xml
- sbnobj/SBND/CRT/CMakeLists.txt
- sbnobj/SBND/CRT/classes.h
- sbnobj/SBND/CRT/classes_def.xml
This PR contains the book-keeping updates to the classes def files and the addition of a needed library.
> Structural changes for clustering objects

- sbnobj/SBND/CRT/CRTEnums.cxx
- sbnobj/SBND/CRT/CRTEnums.hh
This PR introduces some useful enums.
> Add useful enums for CRT sim/reco

- sbnobj/SBND/CRT/CRTStripHit.cxx
- sbnobj/SBND/CRT/CRTStripHit.hh
This PR introduces the new CRTStripHit object which is the basic hit finding object looking for raw data above a threshold and then characterising that within a single CRT strip.
> Add CRTStripHit object

- sbnobj/SBND/CRT/CRTCluster.cxx
- sbnobj/SBND/CRT/CRTCluster.hh
This PR introduces the new CRTCluster object, representing a group of activity in a single tagger.
> Add CRTCluster object

- sbnobj/SBND/CRT/CRTSpacePoint.cxx
- sbnobj/SBND/CRT/CRTSpacePoint.hh
This PR introduces the new CRTSpacePoint object which represents a characterisation of a CRTCluster.
> Add CRTSpacePoint object

- sbnobj/SBND/CRT/CRTTrack.cxx
- sbnobj/SBND/CRT/CRTTrack.hh
This PR introduces the new CRTTrack object, this differs from the sbn::CRTTrack object as there are many unused variables in that object.
> Add CRTTrack object

- sbnobj/Common/Reco/CRUMBSResult.cc
- sbnobj/Common/Reco/CRUMBSResult.h
- sbnobj/Common/Reco/classes_def.xml
Simply adds the new OpT0 CRUMBS variables to the object, main PR is SBNSoftware/sbncode#413
~_This PR requires the (approved) CRT Clustering PRs to be merged first, until then the diff will look huge, it's not._~
> OpT0 CRUMBS

- sbnobj/Common/Trigger/BeamBits.h
- sbnobj/Common/Trigger/ExtraTriggerInfo.cxx
- sbnobj/Common/Trigger/ExtraTriggerInfo.h
- sbnobj/Common/Trigger/classes_def.xml
ICARUS is introducing a complementary trigger based on analogue sum of PMT signals.
This request extends `sbn::ExtraTriggerInfo` to accommodate for this new trigger:
* additional bits (`sectorStatus`) describe the primitive elements of a trigger based on the detector sector (as opposed to the `LVDSstatus` one which refers to specific PMT channels) -- and yes, it should have been `state` instead of `status` but that train has left some time ago;
* an additional flag to state which logic fired the trigger on each cryostat; so far it can be an adder-like value and a majority-like value, or both;
* additional values in the window mode configuration, now supporting the adder triggers in conjunction with the other modes or alone.
These objects have been filled to accommodate ICARUS trigger …
> Adding trigger information for ICARUS

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
Add the t0CRT to the calibration ntuples. Needs to have to equivalent pull request in sbncode [here](https://github.com/SBNSoftware/sbncode/pull/468) also present.
> Add t0CRT to TrackCaloSkimmerObj

- sbnobj/SBND/CRT/FEBData.hh
In data we are using this previously unfilled field to store a cable delay.
This PR just ensures this is documented in the object file itself. We could change the names of the functions etc but that makes the object incompatible with previous code / files so I am inclined not to.
> FEBData Comments

- sbnobj/Common/CRT/CRTPMTMatching.hh
This pull request adds a helper function `assignFlashClassification` that assigns a CRT-PMT Match flashClassification using the number of CRT Hits entering or exiting the detector based on the CRT-PMT Time difference value. The function reads in the number of top, side, or bottom CRT hits entering or exiting the detector and returns a [matchType](https://github.com/SBNSoftware/sbnobj/blob/develop/sbnobj/Common/CRT/CRTPMTMatching.hh#L19). This function will be called in [sbncode PR #482](https://github.com/SBNSoftware/sbncode/pull/482) and can replace these lines in the [CRTPMTMatchingUtils.cxx](https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx#L90C1-L117C35) in icaruscode as well. 
Note: The bottom CRT is currently not used in the …
> add function to assign CRT-PMT Match classificaiton to sbnobj

- sbnobj/Common/Trigger/ExtraTriggerInfo.cxx
- sbnobj/Common/Trigger/ExtraTriggerInfo.h
- sbnobj/Common/Trigger/classes_def.xml
ICARUS trigger hardware is going to contribute one additional information (see e.g. [SBNDocDB 36096](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=36096) or [36264](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=36264)).
This PR extends the `sbn::ExtraTriggerInfo` data product to accommodate for that new information, that is the time from the opening of the beam gate at which the hardware sees the trigger. This is a more direct quantification of that time than with the White Rabbit timestamp, because once the hardware takes the trigger decision, this time is frozen by the very same hardware, while it takes further time (and jitters) for the decision to reach the timestamping hardware. In the ICARUS hardware the time is measured in FPGA ticks, but the data product …
> sbn::ExtraTriggerInfo: added cryostat trigger information

- sbnobj/Common/CRT/CRTPMTMatching.cxx
- sbnobj/Common/CRT/CRTPMTMatching.hh
This is a copy of [sbnobj PR#114](https://github.com/SBNSoftware/sbnobj/pull/114) for the production branch.
> add function to assign CRT-PMT Match classificaiton to sbnobj [release/SBN2024A]

- sbnobj/Common/CRT/CMakeLists.txt
- sbnobj/Common/CRT/CRTPMTMatching.cxx
- sbnobj/Common/CRT/CRTPMTMatching.hh
This PR addresses some final comments by @PetrilloAtWork on sbnobj PR #114. Here I've moved the assignFlashClassification function definition from `sbnobj/Common/CRT/CRTPMTMatching.hh` to a new file `sbnobj/Common/CRT/CRTPMTMatching.cxx`, and also made sure to use `unsigned int` instead of `uint` as suggested in [this comment](https://github.com/SBNSoftware/sbnobj/pull/115#pullrequestreview-2455615721).
> CRTPMTMatching fix: move function definition 

- sbnobj/SBND/CRT/CRTEnums.hh
- sbnobj/SBND/CRT/classes_def.xml
It is useful to have an available enumeration for denoting the status of CRT channels (where 0 is good and 1+ are varieties of bad).
Neighbouring channels to bad channels have their own code due to the nature of the CRT readout. A bad channel neighbour will be suppressed by the bad channel.
This will be used in an sbndcode PR. It will be filled from a text file and used to suppress reconstruction for these channels and provide labeling of them in analysis modules.
> Enumeration for Channel Status

- sbnobj/SBND/Timing/DAQTimestamp.cxx
- sbnobj/SBND/Timing/DAQTimestamp.hh
- sbnobj/SBND/Timing/classes_def.xml
The fix introduces a new variable `timestampPs` in the decoded TDC object `sbnd::timing::DAQTimestamp`.
Enable 2 ways to construct the `sbnd::timing::DAQTimestamp`, with and without `timestampPs` to enable backward compatibility.
In case the object is constructed without `timestampPs`, the variable is defaulted to 0.
In case the object is constructed with `timestampPs`, the variable is  set to the provided value.
> Add ps to decoded TDC, allow 2 different constructors for backward compataibility

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
It is sometimes useful to exclude hits with poor fits when doing analysis with the calibration ntuples. This PR adds a field to store the `recob::Hit::GoodnessOfFit` score to the `sbn::HitInfo` object so that it is available in the calibration ntuples. See corresponding PR in sbncode for implementation in `TrackCaloSkimmer_module.cc`.
Associated sbncode PR: https://github.com/SBNSoftware/sbncode/pull/512
> Add hit goodness to sbn::HitInfo

- sbnobj/SBND/CRT/CRTEnums.hh
With the way the MINOS modules are connected to the readout FEBs 30 (10 each from 3 modules) of the 32 channels on the FEB are connected to a SiPM. This leaves 2 channels per FEB (only 2 FEBs so 4 in total in the system). Which will readout but are not connected to a SiPM, dead or otherwise! I would like to have a simple indication of this and this seems the obvious way to do this.
We don't actually need this category to exist quite yet but I thought of it whilst preparing the CRT inputs to the calibration database and thought it was worth pre-empting given it's a very simple change.
> Add category to enum for unused channel

- sbnobj/SBND/CRT/CRTCluster.cxx
- sbnobj/SBND/CRT/CRTCluster.hh
- sbnobj/SBND/CRT/CRTStripHit.cxx
- sbnobj/SBND/CRT/CRTStripHit.hh
- sbnobj/SBND/CRT/classes_def.xml
As is described in SBNSoftware/sbndcode#705 we require the low-level CRT objects to store timings as doubles not integers from now on. This is due to calibrated timing delays that are fractional.
> Ints -> Doubles for low-level CRT reco

- sbnobj/SBND/Timing/CMakeLists.txt
- sbnobj/SBND/Timing/FrameShiftInfo.cxx
- sbnobj/SBND/Timing/FrameShiftInfo.hh
- sbnobj/SBND/Timing/TimingInfo.cxx
- sbnobj/SBND/Timing/TimingInfo.hh
- sbnobj/SBND/Timing/classes.h
- sbnobj/SBND/Timing/classes_def.xml
Description can be found in docdb: https://sbn-docdb.fnal.gov/cgi-bin/sso/RetrieveFile?docid=43090
Required by the following PRs:
sbnobj 2025A: https://github.com/SBNSoftware/sbnobj/pull/141
sbnanaobj 2025A: https://github.com/SBNSoftware/sbnanaobj/pull/155
sbndcode 2025A: https://github.com/SBNSoftware/sbndcode/pull/803
sbncode 2025A: https://github.com/SBNSoftware/sbncode/pull/563
> Frame Shift Module to Correct Timing in Data - PR For Spring Production

- sbnobj/Common/Calibration/TrackCaloSkimmerObj.h
- sbnobj/Common/Calibration/classes_def.xml
Part of a pair of PRs to enhance the SBND CRT contribution to the calibration ntuples. (See also SBNSoftware/sbncode#557)
This PR:
- Adds a branch for storing the CRTSpacePoint matching T0 value
- Adds two branches that document the matching score quality and the xshift applied (both add analyser flexibility)
Presenting today at the calibration meeting - will link slides after.
> Calib NTuple CRT Timing Additions
